### PR TITLE
add postgis docker and config files

### PR DESCRIPTION
**Pull request by cirnoooo123**

### CODE REVIEW

**Review by Qwtdgh — APPROVED** [review]

**Review by Qwtdgh — APPROVED** [review]
ok

**Review by Qwtdgh — APPROVED** [review]
good

**Comment by Qwtdgh** [comment]
good

**Review by Qwtdgh — APPROVED** [review]

**Review by Qwtdgh — APPROVED** [review]
ok

**Review by neumyor — APPROVED** [review]
accepted

**Pull request merged**
